[package]
name = "merklez"
version = "0.1.0"
authors = ["protolambda <proto@protolambda.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.9"
